--- #YAML:1.0
name:                Filter
version:             1.34
abstract:            Source Filters
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Marquess <pmqs@cpan.org>
